pipeline {
    agent any

    environment {
        IMAGE_NAME = "navbilak/nodejs-app"
        SONAR_PROJECT_KEY = "nodejs-app"
        SONAR_HOST_URL = "http://host.docker.internal:9000"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test (npm install + test)') {
            steps {
                dir('app') {
                    bat 'npm install'
                    bat 'npm test'
                }
            }
        }

        stage('SonarQube Analysis (Docker Scanner)') {
            steps {
                dir('app') {
                    withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                        bat '''
                        docker run --rm ^
                          -e SONAR_HOST_URL=%SONAR_HOST_URL% ^
                          -e SONAR_TOKEN=%SONAR_TOKEN% ^
                          -v "%cd%:/usr/src" ^
                          sonarsource/sonar-scanner-cli ^
                          -Dsonar.projectKey=%SONAR_PROJECT_KEY% ^
                          -Dsonar.sources=.
                        '''
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('app') {
                    bat "docker build -t %IMAGE_NAME%:latest ."
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-token',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    bat '''
                    echo %PASS% | docker login -u %USER% --password-stdin
                    docker push %IMAGE_NAME%:latest
                    '''
                }
            }
        }

        stage('Run Container Locally') {
            steps {
                bat '''
                docker stop node-app || echo "No container to stop"
                docker rm node-app || echo "No container to remove"
                docker run -d -p 3000:3000 --name node-app %IMAGE_NAME%:latest
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Pipeline completed successfully 🚀"
        }
        failure {
            echo "❌ Pipeline failed - check logs"
        }
    }
}
