pipeline {
    agent any

    environment {
        IMAGE_NAME = "navbilak/nodejs-app"   // change if needed
        SONAR_PROJECT_KEY = "nodejs-app"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test (npm install + test)') {
            steps {
                dir('app') {
                    bat 'npm install'
                    bat 'npm test'
                }
            }
        }

        stage('SonarQube Analysis (Docker Scanner)') {
            steps {
                dir('app') {
                    bat '''
                    docker run --rm ^
                      -e SONAR_HOST_URL="http://host.docker.internal:9000" ^
                      -e SONAR_TOKEN=%SONAR_TOKEN% ^
                      -v "%cd%:/usr/src" ^
                      sonarsource/sonar-scanner-cli ^
                      -Dsonar.projectKey=%SONAR_PROJECT_KEY% ^
                      -Dsonar.sources=.
                    '''
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('app') {
                    bat "docker build -t %IMAGE_NAME%:latest ."
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-token',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {

                    bat '''
                    echo %PASS% | docker login -u %USER% --password-stdin
                    docker push %IMAGE_NAME%:latest
                    '''
                }
            }
        }

        stage('Run Container Locally') {
            steps {
                bat '''
                docker run -d -p 3000:3000 %IMAGE_NAME%:latest || exit 0
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Pipeline completed successfully 🚀"
        }
        failure {
            echo "❌ Pipeline failed - check logs"
        }
    }
}
