pipeline {
    agent any

    environment {
        IMAGE_NAME = "navbilak/ci-app"
    }

    stages {

        stage('Test') {
            steps {
                bat 'npm install'
                bat 'npm test'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar') {
                    bat '''
                    sonar-scanner ^
                    -Dsonar.projectKey=ci-app ^
                    -Dsonar.sources=. ^
                    -Dsonar.host.url=http://sonarqube:9000 ^
                    -Dsonar.login=%SONAR_TOKEN%
                    '''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Docker Build') {
            steps {
                bat 'docker build -t %IMAGE_NAME%:latest .'
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-token',
                    usernameVariable: 'USER', passwordVariable: 'PASS')]) {

                    bat '''
                    echo %PASS% | docker login -u %USER% --password-stdin
                    docker push %IMAGE_NAME%:latest
                    '''
                }
            }
        }

        stage('Run Container') {
            steps {
                bat 'docker run -d -p 3000:3000 %IMAGE_NAME%:latest || exit 0'
            }
        }
    }
}
